version: "3.8"

services:
  airflow:
    image: apache/airflow:2.8.0
    container_name: airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
    depends_on:
      - airflow_scheduler

  airflow_scheduler:
    image: apache/airflow:2.8.0
    container_name: airflow_scheduler
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags

  rest_api:
    build:
      context: .
    container_name: rest_api
    ports:
      - "5000:5000"
    depends_on:
      - airflow
